[package]
name = "safe-copy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
cliclack = "0.3.6"
rayon = "1.10.0"
sha2 = "0.10.9"
